import { links } from "../config/links";
import {
  Gmail,
  Javascript,
  Typescript,
  Mysql,
  Realm,
  Mongodb,
  Html5,
  CssThree,
  ReactJs,
  Nodedotjs,
  Nextdotjs,
  Vuedotjs,
  Tailwindcss,
  Spring,
  Scikitlearn,
  Tensorflow,
  Docker,
  Git,
  Redis,
  Postman,
  Nestjs,
  Sass,
  Angular,
  Prisma,
  Kubernetes,
} from "@icons-pack/react-simple-icons";
export const me = {
  site: "https://www.anzifan.com",
  name: "三两三💯",
  bio: "💻 🎮 ⚡️ 🎸",
  social: [
    ...links,
    {
      url: "mailto:1192305489@qq.com",
      icon: Gmail,
      name: "Email",
      fill: "fill-gray-400",
      border: "border-gray-400",
      text: "text-gray-400",
      shadow: "shadow-sky-300",
      color: "from-blue-600 to-sky-300",
    },
  ],
  overview: [],
  education: [
    {
      name: "Northeastern University",
      time: "2021-2022",
      degree: "MS, Computer Software Engineering",
      color: "red",
      logo: "/static/images/neu.png",
    },
  ],
  projects: [
    {
      name: "Astraios",
      description:
        "A GitHub Star Management App, based on SwiftUI and Combine.",
      tip: "Coming Soon on App Store",
      images: [
        "/static/images/Astraios/4.png",
        "/static/images/Astraios/3.png",
        "/static/images/Astraios/2.png",
        "/static/images/Astraios/5.png",
        "/static/images/Astraios/7.png",
      ],
      icon: "/static/images/Astraios/astraios.png",
    },
    {
      name: "Pokémon Recommender",
      description:
        "A iOS Pokédex with an original recommendation algorithm that considers multiple factors",
      tag: ["Web Crawler", "Database Design", "Recommendation algorithm"],
      video: "/static/videos/pokemon.mp4",
      icon: "/static/images/pokemon.png",
    },
  ],
  skills: [
    [
      { name: "Javascript", color: "bg-[#F7DF1E]", icon: Javascript },
      { name: "Typescript", color: "bg-[#3178C6]", icon: Typescript },
      { name: "HTML5", color: "bg-[#E34F26]", icon: Html5 },
      { name: "CSS3", color: "bg-[#1572B6]", icon: CssThree },
      { name: "Vue.js", color: "bg-[#4FC08D]", icon: Vuedotjs },
      { name: "Angular", color: "bg-[#c3002f]", icon: Angular },
      { name: "React", color: "bg-[#61DAFB]", icon: ReactJs },
      { name: "Next.js", color: "bg-[#000000]", icon: Nextdotjs },
      { name: "Tailwind CSS", color: "bg-[#06B6D4]", icon: Tailwindcss },
      { name: "Sass", color: "bg-[#cc6699]", icon: Sass },
      { name: "Node.js", color: "bg-[#339933]", icon: Nodedotjs },
      { name: "Nest", color: "bg-[#e0234e]", icon: Nestjs },
      { name: "Prisma", color: "bg-[#1a202c]", icon: Prisma },
      { name: "MongoDB", color: "bg-[#47A248]", icon: Mongodb },
      { name: "Git", color: "bg-[#F05032]", icon: Git },
      { name: "Postman", color: "bg-[#FF6C37]", icon: Postman },
      { name: "Docker", color: "bg-[#0AA6D8]", icon: Docker },
      { name: "Kubernetes", color: "bg-[#326de6]", icon: Kubernetes },
    ],
  ],
};
